### ISSUE TITLE
Stopped saving email password

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#359]
Recently, I stopped receiving daily email status notices.  

My SMPT settings are correct.  When I enter the password for the email account and click 'Send Test Mail', the email is sent (and received) correctly.  However, when I 'Save configuration SMTP', and then try to Send Test Mail, I receive the following error:

Error : Failed to authenticate on SMTP server with username "info@xxxxxxx.com" using 1 possible authenticators /home/default/html/myddleware/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php Line : ( 181 )

I am 100% certain that I am entering the credentials correctly (particularly, since it does work that one time).

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
Did you change Myddleware before your have stopped receiving daily mail ? Like upgradding Myddleware ?
If no, I would say that your problem is on SMTP side, or server file (firewall), or mail could be sent in your spam mailbox ? 
Could you try to send daily mail to another mailbox to test Myddleware ?
Thanks

**Comment by fosullivan-usam** [comment]
The email does not go to the Junk folder because it is not sent.  I get a very clear error message confirming that it failed to send (see above). Also, as I mentioned above, when I enter the correct password for the email account and click 'Send Test Mail', the email is sent (and received) correctly. However, when I click Send Test Mail again, or click on 'Save configuration SMTP', and then try to Send Test Mail, I receive the error.

No, I did not upgrade Myddleware when it broke.  I last updated Myddleware as soon as version 2.5.4.k was released in early August.  My most recent automatic email was received on September 19th.  

I did change the password for the mail account (i.e., on the SMTP server) and then updated Myddleware with the new password.  

Might Myddleware be failing to save the email password for some reason?  Maybe it a file permission issue on my server, or something in the database?  

Any help would be appreciated.

Thanks,
Feargal

**Comment by Myddleware** [comment]
Ho sorry @fosullivan-usam,

I was too quick to reply. It seems that there is a bug when we save the SMTP parameters. We will have a look into this.

In the meantime, you can try to update your smpt parameters directly in the parameter file here : <myddleware_root>\app\config\public\parameters_smtp.yml

Then clear all your cache by removing the content of the directories <myddleware_root>\var\cache\dev and <myddleware_root>\var\cache\prod

Now Myddleware should be able to send notification by email.

Please keep me updated.

**Comment by fosullivan-usam** [comment]
I edited the file and cleared the cache.  When I logged in and went to the SMTP Configuration page, it changed the password to NULL again.  So, I made the changes again, but will now wait until tomorrow to see if the scheduled email fires on time.  I'll be sure to let you know, but please let me know when you post an update with a fix to this problem.
Thank you!

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
We will try to reproduce the bug and fix it for the next hotfix version.
I 'll keep you updated.

**Comment by AlexMyddleware** [comment]
was solved in later update

**Comment by fosullivan-usam** [comment]
Unfortunately, it's still not working for us.  The ./config/swiftmailer.yaml and ./config/packages/swiftmailer.yaml do save every setting other than the password.  Even if I manually change the password from NULL in the .yaml files, when I try to send, it fails and when I reopen the .yaml files, the password says NULL again.
